"""add_cost_tracking

Revision ID: 10012581a4c6
Revises: f9cfc3bd0d20
Create Date: 2026-04-28 10:17:41.124276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10012581a4c6'
down_revision: Union[str, None] = 'f9cfc3bd0d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_cost_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('execution_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_execution_cost_logs_user_created', 'execution_cost_logs', ['user_id', 'created_at'], unique=False)
    op.add_column('company_profiles', sa.Column('monthly_budget_usd', sa.Float(), server_default='50.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_profiles', 'monthly_budget_usd')
    op.drop_index('ix_execution_cost_logs_user_created', table_name='execution_cost_logs')
    op.drop_table('execution_cost_logs')
    # ### end Alembic commands ###
